#!/usr/bin/env ruby
require 'yaml'

$config_file = "#{ENV['HOME']}/.lunchcfg.yaml"
$config = YAML.load_file $config_file

args = ARGV.flat_map do |arg|
  arg.split(" ").length > 1 ? arg.split(" ") : arg
end

# Executing shorthands
if $config['Shorthands'].keys.include? args[0]
  %x[#{$config['Shorthands'][args[0]]}]
else
  # Determine Filters 
  $filters = []
  args.each_with_index do |arg, i|
    if $config['Filters'].keys.include? arg
      args.delete_at i
      $filters.push $config['Filters'][arg]
    end
  end
  $filters.push $config['Filters'][$config['Filters']['default']] if $filters.length < 1


  shell = false

  # Determine Handlers
  $handlers = []
  args.each_with_index do |arg, i|
    if $config['Handlers'].keys.include? arg
      $filters[0] = "%s" if arg == "sh"
      args.delete_at i
      $handlers.push $config['Handlers'][arg]
    end
  end
  $handlers.push $config['Handlers'][$config['Handlers']['default']] if $handlers.length < 1

  space = $filters[0].include? "://" ? "%20" : " "

  args_output = ""
  args.each do |arg|
    args_output += "#{arg}#{space}"
  end

  command = $filters[0].gsub '%s', args_output
  %x[#{$handlers[0].gsub '%s', command}]
end
