lunch_lists:
  ssh_shorthands:
    handled_by: query_cl
    default_handler: ssh

    entries:
      site5: miles@userbound.com
      dreamhost: bladdo@bladdo.net
      x300: mil@x300
      x40: mil@x40
      pi: mil@pi
