applications:
  default_entree: surf

  entries:
    surf: surf %s
    chromium: chromium %s
    private: chromium --incognito %s
    ff: firefox %s
    https?: surf %s
    xml: newsreader %s
    sh: urxvt -e %s  # Termial Handlers, launch new term
    s: exec %s       # Single command run
