lunch_lists:
  applications:
    # no 'handled_by', or 'default_handler' for top level!

    entries:
      surf: surf %s
      chromium: chromium %s
      private: chromium --incognito %s
      ff: firefox %s
      https?: surf %s
      xml: newsreader %s
      sh: urxvt -e %s  # Termial Handlers, launch new term
      s: exec %s       # Single command run
