lunch_lists:
  applications:
    # no 'handled_by', or 'default_handler' for top level!

    entries:
      surf: surf %s
      chr: chromium %s
      private: chromium --incognito %s
      ff: firefox %s
      https?: surf %s
      xml: newsreader %s

      term: urxvt -e %s
      silent: exec %s

  terminal:
    handled_by: applications
    default_handler: term
    entries:
      editor: vim %s
      ranger: ranger %s
      j: j %s
