lunch_lists:
  ssh:
    appetizer_choice: ssh
    appetizer: $query_cl

    site5: miles@userbound.com
    dreamhost: bladdo@bladdo.net
    x300: mil@x300
    x40: mil@x40

  edit:
    appetizer_choice: editor
    appetizer: $query_cl

    config: /home/mil/.lunchcfg.yaml

  misc:

    # Filebrowser
    ranger      : sh ranger
    brows       : http://localhost:3400
    # Window Manager
    down        : sh i3 focus down
    up          : sh i3 focus up
    left        : sh i3 focus left
    right       : sh i3 focus right
    # Tmux Sessions
    notes       : sh tmx notes
    music       : sh dtach -A /home/mil/IPC/Sockets/music fish -c dvtm
    torrent     : sh dtach -A /home/mil/IPC/Sockets/torrent fish -c dvtm
    irc         : sh dtach -A /home/mil/IPC/Sockets/irc fish -c dvtm
    chat        : sh dtach -A /home/mil/IPC/Sockets/chat fish -c pidgin
    network     : sh tmx network
    system      : sh tmx system

    # Alarm Clock
    wakeup      : sh wakeup
    crontab     : sh crontab -e
    cron        : sh crontab -e

    # Audio
    wuvt        : sh urxvt -fn "xft:Envy Code R-30" -e sleepit 10 wuvt
    bt          : sh urxvt -fn "xft:Envy Code R-30" -e sleepit 10 bt
    mixer       : sh alsamixer
    eq          : sh alsamixer -D equal
    dj          : sh mpctrl

    pause       : s mediaControl pause
    next        : s mediaControl next
    previous    : s mediaControl previous
    mute        : s amixer set Master 0% mute

    # Locations
    campus      : sh campus
    home        : sh home

    # System
    monitor      : s arandr
    remap        : s xmodmap ~/.xmodmap
    viewsonic    : s viewsonic
    dualscreen   : s dualscreen
    singlescreen : s singlescreen
    morning      : s light on
    goodnight    : s xset dpms force suspend && light off
    lock         : s slock
    invert       : s xcalib -a -invert
    suspend      : s sudo pm-suspend
    shutdown     : s sudo /usr/bin/systemctl hibernate
    reboot       : s sudo /usr/bin/systemctl reboot
    halt         : s sudo /usr/bin/systemctl poweroff
    fans         : s fans

    # Games
    clock       : s urxvt -fn "xft:Envy Code R-20" -e tty-clock -c -s -C 2
    tetris      : sh vitetris
    word        : s abiword

    # Tools
    code        : s ranger /home/mil/Code
    edit        : s surf 'http://userbound.com/ui/mil-edit'
    email       : s urxvt -e mutt
    webmail     : s chromium --incognito http://userbound.com/webmail
    download    : s launch '`sselp`'
    auth        : s 'vt_auth'
    netgood     : s ping google.com
    root        : s sudo su
    cron        : s crontab -e
    top         : s htop

    # Bookmarks
    bookmarks   : sh ranger /home/mil/Code/Bitbucket/bookmarks
    otw         : http://onethingwell.org
    hn          : http://news.ycombinator.com
    bb          : http://bitbucket.org
    scholar     : http://scholar.vt.edu

    # Graphics
    calibrate   : sh dispwin
    gimp        : s gimp
    phatch      : s phatch
    picker      : s gcolor2
    ruler       : s xmeasure | tr -d '\n' | xargs -I INF zenity --info --text='INF'
    screenshot  : s scrot
    c           : s xdotool key c l o n e Return

    # Skanote
    skanote-dev : sh chromium --app=http://localhost:9292
    skanote     : sh chromium --app=http://morning-plains-8512.herokuapp.com
